title: Gerbil Engine Documentation 
description: A comprehensive guide to my project.
baseurl: ""  # The base URL for the site (if not hosted at the root)
url: "https://gerbil789.github.io/GerbilEngine"  # Your GitHub Pages URL
theme: jekyll-theme-cayman  # A Jekyll theme (you can choose any theme you like)