title: Gerbil Engine Documentation 
description: A comprehensive guide to my project.
baseurl: "/GerbilEngine"
url: "https://gerbil789.github.io/GerbilEngine"  # Your GitHub Pages URL
theme: jekyll-theme-cayman  # A Jekyll theme (you can choose any theme you like)